server:
  port: 9192
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9191/eureka/